service:
  provider:
    openweathermap:
      application-id: bf00788b08f86dbf6f552e1ac7f01e3c
  polling-interval-ms: 10000
  alert-summary-log-file: alert_summary.json
  alert-settings-file: classpath:default_alert_settings.json